data:
  start_date: '2022-01-01'
  end_date: '2023-12-31'
  universe_size: 30
  selection_size: 15
  market_cap_threshold: 100000000
  exclude_stablecoins: true
  exclude_wrapped: true
  survivorship_bias: true
  data_source: binance
  cache_directory: data
  cache_days: 30
  update_frequency: daily
  min_trading_days: 100
  max_missing_data_pct: 0.05
signals:
  signal_strategy: momentum_score
  adx_periods:
  - 7
  - 14
  - 21
  adx_threshold: 15.0
  base_ewma_span: 20
  adaptive_ewma: true
  momentum_weights:
    price: 0.4
    volume: 0.2
    rsi: 0.2
    macd: 0.2
  absolute_momentum_threshold: 0.05
  relative_momentum_threshold: 0.0
  momentum_lookback: 30
  momentum_threshold: 0.01
  mean_return_ewm_threshold: 0.003
  mean_return_simple_threshold: 0.005
  mean_return_ewm_span: 10
  mean_return_simple_window: 5
  rsi_period: 14
  rsi_oversold: 25.0
  rsi_overbought: 75.0
  macd_fast: 12
  macd_slow: 26
  macd_signal: 9
  min_score_threshold: 0.3
  use_volume_confirmation: true
  volume_threshold: 1.2
  max_correlation: 0.7
portfolio:
  initial_capital: 1000000.0
  max_position_size: 0.25
  min_position_size: 0.02
  base_rebalance_frequency: weekly
  use_dynamic_rebalancing: true
  optimization_method: enhanced_risk_parity
  concentration_mode: true
  top_n_assets: 5
  concentration_weight: 0.6
  momentum_tilt_strength: 0.5
  use_momentum_weighting: true
  target_volatility: 0.25
  max_concentration: 0.3
  category_max_weights:
    defi: 0.4
    layer1: 0.5
    layer2: 0.3
    meme: 0.2
    exchange: 0.3
  consider_transaction_costs: true
  min_trade_size: 500.0
  target_cash_allocation: 0.0
  max_cash_allocation: 0.05
    # Optimization method - now supports 'agnostic_risk_parity'
  optimization_method: agnostic_risk_parity  # Options: enhanced_risk_parity, agnostic_risk_parity, equal_weight
  
  # ARP-specific parameters
  arp_shrinkage_factor: null    # null for pure ARP, 0.0-1.0 for shrinkage toward Markowitz
                                 # 0.0 = pure ARP (Q=I), 1.0 = pure Markowitz (Q=C)
                                 # Recommended: null or 0.0 for maximum robustness
  
  # Target volatility (optional - if not set, uses budget constraint)
  target_volatility: 0.15        # 15% annual volatility target
  
  # Note: When using ARP, these parameters are less relevant:
  # - concentration_mode (ARP naturally diversifies across PCs)
  # - momentum_tilt_strength (signals are incorporated directly)
  # - use_momentum_weighting (momentum is in the signals)
risk:
  max_drawdown: 0.2
  daily_var_limit: 0.05
  position_var_limit: 0.1
  correlation_threshold: 0.7
  max_correlation: 0.7
  max_exchange_exposure: 0.4
  volatility_lookback: 20
  volatility_multiple: 2.0
  volatility_regime_multiplier: 1.5
  use_trailing_stops: true
  trailing_stop_atr_multiplier: 2.5
  atr_period: 14
  atr_multiplier: 2.0
  regime_lookback: 60
  crisis_vol_threshold: 1.0
  use_stop_losses: true
  stop_loss_pct: 0.08
  use_take_profits: false
  take_profit_pct: 0.15
  leverage_limit: 1.0
  sector_concentration_limit: 0.3
  risk_monitoring_frequency: daily
  max_drawdown_threshold: 0.2
  alert_thresholds:
    drawdown_warning: 0.1
    volatility_warning: 0.3
    correlation_warning: 0.6
costs:
  maker_fee: 0.0008
  taker_fee: 0.001
  base_spread: 0.0003
  impact_coefficient: 0.0001
  use_slippage: true
  slippage_coefficient: 0.0002
  max_slippage: 0.005
  funding_rate: 0.0001
  borrow_rate: 0.0002
  fill_probability: 0.95
  partial_fill_threshold: 0.5
  funding_lookback_days: 30
backtest:
  execution_delay: 0
  market_hours_only: false
  benchmark_symbol: BTCUSDT
  risk_free_rate: 0.02
  walk_forward_analysis: true
  walk_forward_splits: 5
  out_of_sample_periods: 60
  monte_carlo_runs: 1000
  save_trades: true
  save_positions: true
  save_metrics: true
  output_directory: output_enhanced
  calculate_attribution: true
  attribution_frequency: monthly
regime_parameters:
  trending:
    exposure_multiplier: 1.5
    rebalance_frequency: daily
    max_position_size: 0.3
    stop_loss_multiplier: 1.2
  volatile:
    exposure_multiplier: 0.5
    rebalance_frequency: weekly
    max_position_size: 0.15
    stop_loss_multiplier: 0.8
  ranging:
    exposure_multiplier: 0.7
    rebalance_frequency: biweekly
    max_position_size: 0.2
    stop_loss_multiplier: 1.0
  crisis:
    exposure_multiplier: 0.3
    rebalance_frequency: daily
    max_position_size: 0.1
    stop_loss_multiplier: 0.6
random_seed: 42
log_level: INFO
parallel_processing: true
max_workers: 4
