# 3. Hybrid Strategy - Momentum + Mean Return Confirmation (config_hybrid.yaml)
# Requires both momentum indicators AND positive mean returns
strategy:
  universe_size: 10
  rebalance_frequency: "weekly"  
  max_position_size: 0.10
  long_short: true

signals:
  # Momentum parameters
  adx_period: 14
  adx_threshold: 25
  ewma_fast: 10
  ewma_slow: 30
  volume_filter_multiple: 1.5
  
  # Mean return as confirmation
  use_mean_return_signal: true
  mean_return_window: 30
  mean_return_type: "ewm"
  mean_return_threshold: 0.005  # 0.5% threshold
  mean_return_ewm_span: 20
  combine_signals: "and"  # Both must agree