costs:
  base_spread: 0.0001
  funding_lookback_days: 30
  maker_fee: 0.0002
  taker_fee: 0.0004
risk:
  atr_multiplier: 4.0
  atr_period: 14
  max_correlation: 0.8
  max_drawdown_threshold: 0.25
  max_exchange_exposure: 0.4
  volatility_regime_multiplier: 1.5
signals:
  adx_period: 14
  adx_threshold: 0.007
  combine_signals: override
  ewma_fast: 2.5
  ewma_slow: 7.5
  mean_return_ewm_span: 5.0
  mean_return_threshold: 0.007
  mean_return_type: ewm
  mean_return_window: 7.5
  use_mean_return_signal: 0.25
  volume_filter_multiple: 0.5
strategy:
  long_short: true
  max_position_size: 0.1
  rebalance_frequency: weekly
  universe_size: 10
