# Enhanced configuration for better performance
data:
  universe_size: 30
  selection_size: 15

signals:
  signal_strategy: ensemble  # Use ensemble of strategies
  momentum_threshold: 0.005  # More sensitive
  min_score_threshold: 0.2   # Lower threshold
  adx_periods: [7, 14, 21]
  adaptive_ewma: true
  use_volume_confirmation: true
  volume_threshold: 1.1      # Lower volume requirement

portfolio:
  optimization_method: enhanced_risk_parity
  max_position_size: 0.30    # Larger positions
  concentration_mode: true
  top_n_assets: 5
  concentration_weight: 0.7
  momentum_tilt_strength: 0.7
  base_rebalance_frequency: daily
  use_dynamic_rebalancing: true

risk:
  max_drawdown: 0.25         # Allow more drawdown
  use_trailing_stops: true
  trailing_stop_atr_multiplier: 2.0
  regime_lookback: 30        # Faster regime detection

backtest:
  walk_forward_analysis: false
  output_directory: output_enhanced
