name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Run tests
      run: |
        pytest tests/ -v --cov=crypto_momentum_backtest

    - name: Run linting
      run: |
        pip install flake8 black mypy
        flake8 crypto_momentum_backtest/ --max-line-length=100
        black --check crypto_momentum_backtest/
        mypy crypto_momentum_backtest/ --ignore-missing-imports